vld:
- name: mgmtnet
  vim-network-name: osm-ext
additionalParamsForVnf:
- member-vnf-index: powerdns
  additionalParamsForKdu:
  - kdu_name: powerdns
    additionalParams:
      # replicaCount: 2  
      # service.loadBalancerIP: '172.21.251.X' # MetalLB IP Address
      # service.type: NodePort
      service:
        type: NodePort
        # loadBalancerIP: '172.21.251.X' # MetalLB IP Address
      env:
        TZ: "Europe/Athens"
